### ISSUE TITLE
define review, post

### ISSUE THREAD

**Issue by seoljiwon** [TeamNado-Sunbae/NadoSunbae-Server#303]
### review와 post의 관계 
**논의 배경:**

 `classroomPost -> post`, `reviewPost -> review` 변경으로 인해 review를 post로 봐야 하는지 의문이 생깁니다. 그동안은 reviewPost라고 되어있으니 post의 속성을 가진다 생각하고 구조를 설계했지만, classroomPost 대신 범용적인 post 워딩을 쓰는 만큼 review를 post로 생각하면 집합 관계가 생기는 것 같아 제대로 정의하려 합니다.

구체적인 변경 사항은 아래와 같습니다.
- likeDB `post_id -> target_id`, `post_type_id -> like_type_id` & 관련 type refactor 
- relation_review_tag DB `post_id -> review_id`
- inappropriate_review `post_id -> review_id`
- review DB 쿼리명에서 post 사용 x

 **변경 이유:** 
 
      1) 결론적으로 review는 post에 포함되지 않는 것으로 생각하려 함. review는 학과 리뷰, post는 일반적인 게시글로 다른 속성을 가지는 게 좋을 것이라 생각.
      
      2) 댓글을 like 하는 등 확장성을 생각하면 likeTypeId가 어울림. (실제로 다른 DB도 개별 typeId를 가지도록 되어 있음.)

   likeTypeId - 좋아요 할 수 있는 대상 타입 
   postTypeId - post DB에 존재하는 게시글 타입, `exclude review`
   (postTypeId에는 1이 필요 없어졌지만, 혼란을 방지하기 위해 postTypeId에서 1은 비우는 것으로 함.)
   [링크 확인 - swagger 쓰면 type 따로 전달해야 하니까 body, params, query에 필요한 경우 여기 쌓으면 좋을 것 같아요.](https://www.notion.so/nadosunbae/Type-a9138b9c92ab4ac7bf774c0af86c6df8)

---
reportDB도 변수명 좀 깔끔하게 `reported_target_id -> target_id`, `reported_target_type_id -> report_type_id`로 바꾸면 통일성이 생기는 느낌일 것 같은데 이건 서비스 로직상 필수적인 부분은 아닌 것 같아서 아직 변경 안했습니다. 우리끼리 컨벤션 만들어 나가는 느낌이라 바꿀지 고민 중인데 의견 궁금해요.

**Comment by seoljiwon** [comment]
답변은 아래 내용 변경할지 말지, 다른 방법 있는지

likeDB post_id -> target_id, post_type_id -> like_type_id & 관련 type refactor
relation_review_tag DB post_id -> review_id
inappropriate_review post_id -> review_id

이것도 변경할지 말지로 달아주시면 됩니당
reported_target_id -> target_id, reported_target_type_id -> report_type_id

**Comment by wngus4296** [comment]
1. 좋은 것 같습니다. post - review를 아예 분리한다고 생각하고 로직을 짜는 게 수월할 것 같네요! post_type_id -> like_type_id에서 target_type_id도 나쁘지 않은 것 같아요~!

2. 얘네도 같이 변경하는 게 좋을 것 같아요! 추가로 reported_target_type_id -> report_type_id 이부분도 뒤에 target_type_id도 괜찮은 것 같습니다.

두 개 다 target_type_id로 해서 헷갈린다면 다른 네이밍도 좋은 것 같아여~

**Comment by seoljiwon** [comment]
넵 둘 다 target_type_id로 변경하는 것도 좋을 것 같아요. 갠적으로 pk는 다 id 쓰는 것처럼 헷갈림은 없지 않을까 생각합니당

**Comment by eunji8784** [comment]
1. review 관련 DB에서 post_id -> review_id로 모두 변경하는거 동의합니다. 구분하기 편할 것 같네용 굿!!
2. 저도 주현이 의견대로 like_type_id, report_type_id 모두 target_type_id로 통일하는 게 개인적으론 더 편할 것 같습니다. 원래대로 해도 상관은 없습니다!

깔끔하게 정리해줘서 고마워용~ 지원선배 최고 !!!
