### ISSUE TITLE
get review of all major of one school

### ISSUE THREAD

**Issue by wngus4296** [TeamNado-Sunbae/NadoSunbae-Server#308]
더보기 클릭 후 나오는 후기글 리스트에서 5개만 뽑아서 홈 메인에 보여지는 것이기 때문에 api 하나만 만듭니다.
response에는 더보기 클릭 후 나오는 후기글에 보이는 정보들을 모두 담습니다.
클라쪽에서 메인에서는 최대 5개만 사용하면 될 것 같습니다.

- 홈 탭 메인의 모든 학과의 후기 최신순
<img width="245" alt="image" src="https://user-images.githubusercontent.com/58043306/183240880-5552a3fe-6e12-4e3f-a3c7-5fedf0913f95.png">

- 홈 탭의 후기 더보기를 클릭했을 때 나오는 후기글 리스트
<img width="243" alt="image" src="https://user-images.githubusercontent.com/58043306/183240896-9a0c25f6-2d0b-4a6a-ba91-37504d059be2.png">

### TODO
- [x] 후기글 0개일 때 res 수정 (클라에서 204로 판단한다고 함)

**Comment by seoljiwon** [comment]
기존 reviewList POST가 좀 더 필터링이 들어간 거니까 /major 같은 거 달고 이게 GET /review 를 가져갔으면 좋겠다는 생각인데 어떨까요?
어차피 HTTP METHOD가 다르긴 하지만 더 명확히 이해하기 위해서요!

**Comment by wngus4296** [comment]
> 기존 /review POST가 좀 더 필터링이 들어간 거니까 /major 같은 거 달고 이게 GET /review 를 가져갔으면 좋겠다는 생각인데 어떨까요? 어차피 HTTP METHOD가 다르긴 하지만 더 명확히 이해하기 위해서요!

좋습니다! 해당 작업할 때 반영하도록 할게요~~

**Comment by seoljiwon** [comment]
> > 기존 /review POST가 좀 더 필터링이 들어간 거니까 /major 같은 거 달고 이게 GET /review 를 가져갔으면 좋겠다는 생각인데 어떨까요? 어차피 HTTP METHOD가 다르긴 하지만 더 명확히 이해하기 위해서요!
> 
> 좋습니다! 해당 작업할 때 반영하도록 할게요~~

넵 /major는 깊게 생각 안해보고 말한 거라 개발하면서 더 좋은 워딩 있으면 바꿔주세용
