### ISSUE TITLE
change status code 200 to 201 when create data

### ISSUE THREAD

**Issue by wngus4296** [TeamNado-Sunbae/NadoSunbae-Server#313]
* 현재 데이터 생성 시 status code가 200으로 반환되고 있음. -> 201로 변경

**Comment by seoljiwon** [comment]
좋네용 이거 클라에서 200대로 처리하고 있을까요? 알려줘야 할 필요가 있는지 궁금합니다

**Comment by wngus4296** [comment]
200만 하고 있거나 200..<300 이런식으로 200대 전체를 success로 하고 있을 수도 있어여! 200만 처리하고 있다면 알려줘야해서 수정하고 바로 공지할 예정입니당
