### ISSUE TITLE
Improve query speed

### ISSUE THREAD

**Issue by wngus4296** [TeamNado-Sunbae/NadoSunbae-Server#314]
* 여러개의 쿼리를 실행 할 경우 속도를 개선합니다.

**Comment by seoljiwon** [comment]
이거 정확히 무슨 의미일까용? #301과 같은 의미라면 close as not planned로 닫아도 좋을 것 같고, 개발하면서 같이 진행할 수 있는 거면 refactor하면서 신기능 개발해도 좋을 것 같아용!

**Comment by wngus4296** [comment]
이거 이번에 제 pr 보시면 
```
const [invisibleUserList, relationReviewTagList] = await Promise.all([
      blockDB.getInvisibleUserListByUserId(client, req.user.id),
      relationReviewTagDB.getRelationReviewTagList(client),
    ]);
```
이런식으로 꼭 위에 쿼리 결과물이 있어야 돌아가는 쿼리가 아니면 한 번에 돌리려구요!

**Comment by wngus4296** [comment]
> 아하아하 안 그래도 진짜 똑같은 블로그 봤었어요 ㅋㅋㅋ 덕분에 공부했습니다 일단 DB단에서 최대한 join해서 가져와보고(#301 내용) 그래도 따로 가져와야 하는 게 있으면 이렇게 하시죵!

ㅋㅋㅋㅋ좋습니다!! 🔥

**Comment by wngus4296** [comment]
해당 이슈는 일단 보류하고 나머지 작업한 후에 진행하겠습니다~!
