### ISSUE TITLE
fix routing of get review list

### ISSUE THREAD

**Issue by wngus4296** [TeamNado-Sunbae/NadoSunbae-Server#315]
현재 후기 조회에서 get 대신 post로 쓰고 있음 -> get으로 변경
* 배열 형태로 가져오는 문제 해결 필요

<img width="655" alt="image" src="https://user-images.githubusercontent.com/58043306/183257505-70f3c4b5-7e15-4a06-9490-6ac823fc1b0e.png">

**Comment by wngus4296** [comment]
추가로 후기글 0개일 때 res 204 -> 200으로 수정

**Comment by seoljiwon** [comment]
https://stackoverflow.com/questions/6243051/how-to-pass-an-array-within-a-query-string
이거 클라분들한테 한 번 확인해보고 GET으로 바꿔도 될 것 같아요

**Comment by wngus4296** [comment]
넵 클라분들께 확인해보고 변경하겠습니다!

**Comment by wngus4296** [comment]
<img width="373" alt="image" src="https://user-images.githubusercontent.com/58043306/184499410-09428087-17ab-41a7-b86b-8d1c66a479f5.png">
