### ISSUE TITLE
update production DB

### ISSUE THREAD

**Issue by seoljiwon** [TeamNado-Sunbae/NadoSunbae-Server#321]
refactoring에 따른 변경
- [x] classroom_post `classroomPost -> post`, 
- [x] review_post`reviewPost -> review`

- [x] likeDB `post_id -> target_id`, `post_type_id -> target_type_id`
- [x] relation_review_tag DB `post_id -> review_id`
- [x] inappropriate_review DB `post_id -> review_id`
- [x] report DB `reported_target_id -> target_id`, `reported_target_type_id -> target_type_id`

- [x]  like DB post_type_id = 2, 3, 4 -> 2로 UPDATE 하는 쿼리 실행

- [x] user DB에 bio 컬럼
- [x] image DB에 type 컬럼

**Comment by seoljiwon** [comment]
UPDATE "like"
    SET target_type_id = 2
    WHERE target_type_id IN (2, 3, 4)
returning *

**Comment by seoljiwon** [comment]
학과 무관 university 1 추가 id 128 (isFirstMajor false, isSecondMajor false)

다른 university도 학과 무관, 미진입 id 붙여서 사용하기로 함

**Comment by seoljiwon** [comment]
새로운 학교 전공리스트 업데이트

**Comment by seoljiwon** [comment]
imageDB -> bannerDB(id, image_url, redirect_url, created_at, updated_at, is_deleted, type)

**Comment by seoljiwon** [comment]
subscribeDB 추가

**Comment by wngus4296** [comment]
서울여대, 중앙대 더미 최종본 수정 완료. (전공, 유저 넣고 유저id 반영해서 후기글 넣기)

**Comment by wngus4296** [comment]
커뮤니티, 과방 1:1 글 더미 넣기

**Comment by wngus4296** [comment]
대규모 업데이트 푸시 알림 전송
